#!/bin/sh
if [ -z "$1" ]
then
echo "Usage: ./song MIDNAME"
else
if [ ! -d "$1" ]
then
mkdir "$1"
fi
tracks=$(./Midicsv "$1.mid" | perl/bin/perl tracks.pl)
track=1
until [ $track -gt $tracks ]
do
./Midicsv "$1.mid" | perl/bin/perl midicsv2frequency.pl $track > "$1/$1$track"
if [ ! -s "$1/$1$track" ]
then
rm "$1/$1$track"
fi
track=$(($track+1))
done
fi